[package]
name = "le-panier-sur"
version = "0.1.0"
description = "Le Panier-Sûr — galerie & identification de champignons"
authors = ["BenjaminGott"]
edition = "2021"

[lib]
name = "le_panier_sur_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
